name: "Bug"
description: "Algo que funciona mal"
labels: ["bug"]
body:
  - type: input
    id: modulo
    attributes:
      label: Módulo
      placeholder: p.ej: Rivales / Plantel
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      placeholder: 1) Ir a… 2) Click en… 3) Esperaba… 4) Ocurre…
  - type: textarea
    id: evidencia
    attributes:
      label: Evidencia
      placeholder: Screenshots / preview
  - type: textarea
    id: impacto
    attributes:
      label: Impacto
      placeholder: A quién afecta y urgencia
