name: "Feature"
description: "Nueva funcionalidad o mejora"
labels: ["feature"]
body:
  - type: input
    id: modulo
    attributes:
      label: Módulo
      placeholder: p.ej: Rivales / Plan semanal / RPE / Clínico
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: Qué queremos lograr (sin tecnicismos)
  - type: textarea
    id: criterios
    attributes:
      label: Criterios de aceptación
      placeholder: "Dado… Cuando… Entonces…"
  - type: textarea
    id: notas
    attributes:
      label: Notas
      placeholder: Links, referencias, mockups
